"""renaming user_uuid to user_uid

Revision ID: 521065244710
Revises: eb127cf5b776
Create Date: 2025-09-24 14:57:02.809023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '521065244710'
down_revision: Union[str, Sequence[str], None] = 'eb127cf5b776'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uid', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('books_user_uuid_fkey'), 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_uid'], ['uid'])
    op.drop_column('books', 'user_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key(op.f('books_user_uuid_fkey'), 'books', 'users', ['user_uuid'], ['uid'])
    op.drop_column('books', 'user_uid')
    # ### end Alembic commands ###
