"""relate users to books

Revision ID: eb127cf5b776
Revises: 74d47df46103
Create Date: 2025-09-24 14:35:03.560632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb127cf5b776'
down_revision: Union[str, Sequence[str], None] = '74d47df46103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_uuid', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'books', 'users', ['user_uuid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'user_uuid')
    # ### end Alembic commands ###
